### ISSUE TITLE
python2: DejaVuSans.ttf not found

### ISSUE THREAD

**Issue by nd2s** [creckx/InvoiceGenerator#9]
reportlab.pdfbase.ttfonts.TTFError: Can't open file "/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf"

Fonts are installed on another path on my system (only know about Arch Linux right now, can test on FreeBSD too if needed).

    user@machine [1] % locate DejaVuSans.ttf                                    
    /usr/share/fonts/TTF/DejaVuSans.ttf
    /usr/share/texmf-dist/fonts/truetype/public/dejavu/DejaVuSans.ttf

**Comment by steephill-mhernandez** [comment]
was this ever closed out?

**Comment by creckx** [comment]
Fonts are part of the repo now, but setup.py doesn't install them yet. I will fix this soon.

**Comment by nodeit** [comment]
I was able to get it working by downloading the fonts, creating the usr/share folder:

http://dejavu-fonts.org/wiki/Download

**Comment by radlws** [comment]
The fonts are there for me in ubuntu 14.04 but in the wrong dir, so just had to copy, 

    sudo cp -rp /usr/share/fonts/truetype/dejavu/ /usr/share/fonts/truetype/ttf-dejavu/

**Comment by nd2s** [comment]
Obviously the fonts can be copied, but messing around with ones system is not a fix.

**Comment by radlws** [comment]
You're not really messing around, just installing fonts manually to the expected dir.

**Comment by nd2s** [comment]
Putting fonts into a directory where they don't belong is messing around.

**Comment by radlws** [comment]
No you're installing it into the proper directory /usr/share/fonts/  

Check this out: http://www.techrepublic.com/blog/linux-and-open-source/how-do-i-install-and-use-fonts-in-linux/

Then go learn some linux

**Comment by nd2s** [comment]
You are wrong. First, that depends on the distribution, and second this ticket is not only about Linux. FreeBSD for example has 3rd party stuff in /usr/local - proper font dir would be /usr/local/share/fonts

**Comment by radlws** [comment]
Nope, I'm not. Just use a symbolic link then or don't bother fixing the problem.. whatever!

**Comment by deronnax** [comment]
Hi.
I just ran into this bug today and this is a very serious one. It absolutely needs to be re-open. The way you handle fonts is plain wrong. It's entirely up to the OS where fonts are stored, so a harcoded path is really plain wrong. For example, on my Fedora, the DejaVuSans fonts are installed in /usr/share/fonts/dejavu/.  
And you're not supposed to tamper with what's inside your /usr/*. Everything under /usr & co is to be managed by your package manager. That's how you manage font on Linux. If you put your things manually there, it's going to be blown away by the next OS update.
Each OS has its standards about where fonts are stored. Because fonts location is not standard. How to get theses locations is tricky and OS dependent. This is partly described there :
https://mail.python.org/pipermail/python-list/2013-July/652065.html. Long story short: on Linux you need to parse /etc/fonts/fonts.conf.

The Ubuntu documentation also makes my point https://wiki.ubuntu.com/Fonts#Manually. 

And the article of TechRepublic has been written by a newbie who should run and hide. 
And radzhome, you're ultra-wrong. Tell me : how are you going to cp your fonts in /usr/share/fonts/truetype/dejavu/ on Windows and MacOS X ?

So please re-open, and unless this is fixed with a proper font locations detection algorithm/library, consider InvoiceGenerator is badly broken, because it doesn't work outside of the very version of the Ubuntu you created it on. And it might break on the next Ubuntu release.
